"""Generate recorded demo audio for 5 test conversation flows.

Produces one MP3 per bot/user utterance, plus a combined per-flow MP3
(bot and user voices alternate) and a README. Uses Google's free TTS
(gTTS) — requires internet on first run.

Usage:
    .venv/bin/python scripts/generate_demo_audio.py [--flows 1 2 3 4 5]
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "backend"))

from app.conversation.engine import ConversationEngine  # noqa: E402
from app.llm.fallback import FallbackProvider  # noqa: E402

OUT_DIR = Path(__file__).resolve().parent.parent / "demo_audio"

# flow_id -> (title, [caller messages])
FLOWS: dict[str, tuple[str, list[str]]] = {
    "1": (
        "Qualified lead - weekend home, full journey",
        [
            "Yes, please go ahead",
            "It's for my own weekend home",
            "Yes, I'm comfortable with the location",
            "Yes, budget is fine",
            "2029 works for me",
            "That sounds lovely",
            "Yes, please call me",
            "My name is Rahul, my number is 9876543210, evening is fine",
        ],
    ),
    "2": (
        "Qualified lead - NRI investment",
        [
            "Go ahead",
            "It's for investment purposes",
            "Yes, the location works",
            "Around 2 crore is my budget",
            "December 2029 is fine",
            "Sounds great",
            "Yes, my name is Priya and my number is 9988776655",
        ],
    ),
    "3": (
        "Budget mismatch - lead closes gracefully",
        [
            "Sure, you may speak",
            "For investment",
            "Yes, location is fine",
            "That's too expensive for me",
            "I can't stretch beyond 70 lakh",
        ],
    ),
    "4": (
        "Location mismatch - lead closes gracefully",
        [
            "Okay, go on",
            "For my own home",
            "Too far for me",
            "No, it's not convenient",
        ],
    ),
    "5": (
        "Irritated caller + Hindi flow (bilingual bonus)",
        [
            "Stop calling me, this is a waste of time",
        ],
    ),
}


def _tts(text: str, out: Path, lang: str = "en") -> None:
    from gtts import gTTS

    tts = gTTS(text=text, lang=lang, tld="co.in" if lang == "en" else None)
    tts.save(str(out))


def _lang_for(turn: str) -> str:
    """Heuristic: pick Hindi TTS for Hindi-language replies."""
    if any(ch in turn for ch in "कखगघचछजझटठडढणतथदधनपफबभमयरलवशषसह"):
        return "hi"
    if any(w in turn.lower() for w in ("haan", "nahi", "dhanyavaad", "aapka", "hai", "main", "kya")):
        return "hi"
    return "en"


import asyncio


def generate_flow(flow_id: str, title: str, messages: list[str]) -> None:
    engine = ConversationEngine(provider=FallbackProvider())

    async def _run():
        start = await engine.start()
        turns: list[tuple[str, str]] = [("agent", start["reply"])]
        for msg in messages:
            turns.append(("caller", msg))
            t = await engine.respond(msg)
            turns.append(("agent", t["reply"]))
            if t["closed"]:
                break
        return turns

    turns = asyncio.run(_run())

    flow_dir = OUT_DIR / f"flow_{flow_id}"
    flow_dir.mkdir(parents=True, exist_ok=True)
    clips: list[str] = []
    for i, (role, text) in enumerate(turns, start=1):
        lang = _lang_for(text)
        clip = flow_dir / f"{i:02d}_{role}.mp3"
        try:
            _tts(text, clip, lang=lang)
        except Exception as exc:  # network / gTTS hiccup
            print(f"  ! TTS failed for clip {i}: {exc}")
            continue
        clips.append(str(clip))
        print(f"  clip {i:02d} [{role}] ({lang}) ok")

    if clips and shutil.which("ffmpeg"):
        combined = OUT_DIR / f"flow_{flow_id}.mp3"
        with open(flow_dir / "clip_list.txt", "w") as f:
            for c in clips:
                f.write(f"file '{Path(c).resolve()}'\n")
        subprocess.run(
            ["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(flow_dir / "clip_list.txt"),
             "-c", "copy", str(combined)],
            check=True, capture_output=True,
        )
        print(f"  combined -> {combined}")


def write_readme() -> None:
    lines = [
        "# Recorded demo calls — Whispers of the Wind voice agent",
        "",
        "Generated by scripts/generate_demo_audio.py using Google free TTS (gTTS).",
        "Each flow_XX.mp3 alternates caller and agent voices (agent clips in demo_audio/flow_XX/).",
        "",
    ]
    for fid, (title, msgs) in FLOWS.items():
        lines.append(f"- **flow_{fid}.mp3** — {title}")
    (OUT_DIR / "README.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--flows", nargs="*", default=list(FLOWS), choices=list(FLOWS))
    args = parser.parse_args()

    OUT_DIR.mkdir(exist_ok=True)
    for fid in args.flows:
        title, msgs = FLOWS[fid]
        print(f"[flow {fid}] {title}")
        generate_flow(fid, title, msgs)
    write_readme()
    print("\nDone. See demo_audio/README.md")


if __name__ == "__main__":
    main()